language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
addons:
  chrome: stable
node_js:
  - stable
  - '10'
before_install:
install:
  - yarn
script:
  - npm run build
  - npm run test
  - npm run report
